# -*- coding: utf-8 -*-
"""Evaluate_Music.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUkuhJFTwxbnJynXUs68BPdeO5fqVxrO
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import json
import pretty_midi
from collections import Counter


def get_metrics_from_midi(midi_path):
    song = pretty_midi.PrettyMIDI(midi_path)

    pitches, velocities, times, durations = [], [], [], []
    for instrument in song.instruments:
        if instrument.is_drum:
            continue
        for note in instrument.notes:
            pitches.append(note.pitch)
            velocities.append(note.velocity)
            times.append((note.start, note.end))
            durations.append(note.end - note.start)

    if not pitches:
        return None

    length = song.get_end_time()

    boundaries = sorted(set([point for start, end in times for point in [start, end]]))
    simultaneous = []
    for index in range(len(boundaries) - 1):
        middle = (boundaries[index] + boundaries[index+1]) / 2
        simultaneous.append(sum(1 for start, end in times if start <= middle <= end))

    pitch_counts = Counter(pitches)
    total = sum(pitch_counts.values())
    entropy = -sum((count/total) * np.log2(count/total) for count in pitch_counts.values())

    pitch_class_counts = Counter([pitch % 12 for pitch in pitches])
    pitch_class_entropy = -sum((count/total) * np.log2(count/total) for count in pitch_class_counts.values())

    return {
        'pitch_range': max(pitches) - min(pitches),
        'n_pitches_used': len(set(pitches)),
        'avg_pitch': np.mean(pitches),
        'avg_velocity': np.mean(velocities),
        'velocity_std': np.std(velocities),
        'total_notes': len(pitches),
        'note_density': len(pitches) / length,
        'avg_note_duration': np.mean(durations),
        'total_duration': length,
        'polyphony': np.mean(simultaneous) if simultaneous else 1.0,
        'max_polyphony': max(simultaneous) if simultaneous else 1,
        'pitch_entropy': entropy,
        'pitch_class_entropy': pitch_class_entropy,
    }


all_results = []

for emotion in ['sad', 'happy', 'calm']:
    for suffix in ['_medium', '_long', '_extended', '']:
        path = f"{emotion}{suffix}.mid"
        if not os.path.exists(path):
            continue
        metrics = get_metrics_from_midi(path)
        if metrics:
            metrics['file'] = Path(path).name
            metrics['emotion'] = emotion
            metrics['type'] = 'generated'
            all_results.append(metrics)

TRAINING_LABELS = {
    'AutumnLeaves.mid': 'calm', 'AllTheThings V2.mid': 'calm',
    'BlueBossa1GM.mid': 'happy', 'BlueBossa3GM.mid': 'happy',
    'DaysofWine.mid': 'sad', 'Georgia.mid': 'sad',
    'Lullaby.mid': 'calm', 'milestones.mid': 'happy',
    'Mood Indigo - solo.mid': 'sad', 'MyFunny3.mid': 'sad',
}

if Path("midi_files").exists():
    seen = {'sad': 0, 'happy': 0, 'calm': 0}
    for file in Path("midi_files").glob("*.mid"):
        if file.name in TRAINING_LABELS and seen[TRAINING_LABELS[file.name]] < 5:
            metrics = get_metrics_from_midi(str(file))
            if metrics:
                metrics['file'] = file.name
                metrics['emotion'] = TRAINING_LABELS[file.name]
                metrics['type'] = 'training'
                all_results.append(metrics)
                seen[TRAINING_LABELS[file.name]] += 1

dataframe = pd.DataFrame(all_results)

if len(dataframe) > 0:
    to_plot = [column for column in ['pitch_range', 'n_pitches_used', 'note_density',
                            'polyphony', 'avg_velocity', 'pitch_entropy'] if column in dataframe.columns]

    rows = (len(to_plot) + 1) // 2
    figure, axes = plt.subplots(rows, 2, figsize=(14, 5 * rows))
    axes = axes.flatten()

    for index, metric in enumerate(to_plot):
        axis = axes[index]
        for position, filetype in enumerate(dataframe['type'].unique()):
            subset = dataframe[dataframe['type'] == filetype]
            values = [subset[subset['emotion'] == emotion][metric].mean() if len(subset[subset['emotion'] == emotion]) > 0 else 0
                    for emotion in dataframe['emotion'].unique()]
            offset = (position - 0.5) * 0.35
            axis.bar(np.arange(len(dataframe['emotion'].unique())) + offset, values, 0.35,
                   label=filetype.capitalize(), alpha=0.8)

        axis.set_xticks(np.arange(len(dataframe['emotion'].unique())))
        axis.set_xticklabels(dataframe['emotion'].unique())
        axis.set_title(metric.replace('_', ' ').title())
        axis.legend()
        axis.grid(axis='y', alpha=0.3)

    for index in range(len(to_plot), len(axes)):
        axes[index].set_visible(False)

    plt.tight_layout()
    plt.savefig('evaluation_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

cleaned = []
for result in all_results:
    cleaned.append({key: float(value) if isinstance(value, (np.integer, np.floating)) else value
                    for key, value in result.items()})

with open('evaluation_results.json', 'w') as file:
    json.dump(cleaned, file, indent=2)