# -*- coding: utf-8 -*-
"""Generate_Music.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nP8quI_1L4AWCrkncRUjbpQsBHTrH-Rd
"""

!pip install transformers torch symusic music21 miditok safetensors -q

import torch
import torch.nn as nn
from transformers import GPT2LMHeadModel, GPT2Config
import symusic
import numpy as np
from pathlib import Path
from tqdm import tqdm
import os, zipfile, random
from music21 import converter, midi as m21midi

EMOTION_LABELS = {
    'AutumnLeaves.mid': 'calm', 'AllTheThings V2.mid': 'calm', 'BlueBossa1GM.mid': 'happy',
    'BlueBossa3GM.mid': 'happy', 'Caravan2.mid': 'happy', 'Come Rain or Come Shine V1.mid': 'calm',
    'Come Rain or Come Shine duo.mid': 'calm', 'DaysofWine.mid': 'sad', 'Easy Living 3.mid': 'calm',
    'Georgia.mid': 'sad', 'Green Dolph solo.mid': 'calm', 'Have You Met - duet.mid': 'happy',
    'Have You Met Miss Jones - latin.mid': 'happy', 'How Deep is the Ocean (Doug McKenzie).mid': 'sad',
    'howdsolo.mid': 'sad', 'hwdptrio.mid': 'sad', 'I Fall in Love v2.mid': 'sad',
    'I fall in Love Too Easily.mid': 'sad', 'I Hear a Rhapsody.mid': 'calm', 'ILoveYou.mid': 'calm',
    'Inasent.mid': 'calm', 'Inasent2.mid': 'calm', 'It Could Happen - piano trio.mid': 'calm',
    'It Could Happen V2.mid': 'calm', 'ItCouldHappenGM.mid': 'calm', 'Just Friends Trio.mid': 'happy',
    'justfrien solo.mid': 'happy', 'laura.mid': 'sad', 'Lullaby.mid': 'calm', 'milestones.mid': 'happy',
    'Mood Indigo - solo.mid': 'sad', 'My Romance.mid': 'calm', 'MyFunny3.mid': 'sad', 'Nardis.mid': 'calm',
    'Out of Nowhere 1.mid': 'calm', 'Out of Nowhere 2.mid': 'calm', 'Out of Nowhere 3.mid': 'calm',
    'Over the rain trio.mid': 'happy', 'OverTheRainbowGM.mid': 'happy', 'OverTheRainbowXG.mid': 'happy',
    'PeacePiece.mid': 'calm', 'Prelude to a kiss.mid': 'sad', 'Skylark 2.mid': 'calm',
    'SoinLovesolo.mid': 'calm', 'SoInlove - trio version.mid': 'calm', 'SomeDayMy.mid': 'calm',
    'Some day My Prince.mid': 'calm', 'SophisticatedLady.mid': 'calm', 'Stella solo.mid': 'calm',
    'taketheatrain.mid': 'happy', 'There will never be another you.mid': 'calm',
    'TheSongisYoutrio.mid': 'happy', 'Time after Time 2.mid': 'calm', 'Very Early solo piano.mid': 'calm',
    'What is this thing - solo.mid': 'happy', 'When I Fall in Love.mid': 'calm', 'youhavechanged.mid': 'sad',
    'funny val solo.mid': 'sad',
}


def extract_and_convert(zip_path="MusicXML_Files.zip", out="midi_files"):
    os.makedirs(out, exist_ok=True)
    os.makedirs("musicxml_extracted", exist_ok=True)
    if not os.path.exists(zip_path): return 0

    with zipfile.ZipFile(zip_path,'r') as z:
        z.extractall("musicxml_extracted")

    xmls = []
    for ext in ['*.xml','*.mxl','*.musicxml']:
        xmls += [f for f in Path("musicxml_extracted").rglob(ext) if not f.name.startswith('._')]

    cnt = 0
    for x in tqdm(xmls, desc="Converting MusicXML to MIDI"):
        try:
            s = converter.parse(str(x))
            mf = m21midi.translate.music21ObjectToMidiFile(s)
            mf.open(os.path.join(out, x.stem+".mid"), 'wb')
            mf.write()
            mf.close()
            cnt += 1
        except: continue
    return cnt


# pytorch needs this to be a module
class EmotionPrompts(nn.Module):
    def __init__(self):
        super().__init__()
        self.prompts = nn.ParameterDict({
            'sad': nn.Parameter(torch.randn(12, 1024) * 0.02),
            'happy': nn.Parameter(torch.randn(12, 1024) * 0.02),
            'calm': nn.Parameter(torch.randn(12, 1024) * 0.02)
        })
    def get(self, emotion): return self.prompts[emotion]


# sad/happy/calm each get diff scales, tempos, chords
SAD_PARAMS = {
    'scale': [0,2,3,5,7,8,10], 'root': 60, 'tempo': 65,
    'chords': [[0,3,7],[5,8,0],[3,7,10],[7,10,2]],
    'rhythm': [1.0,0.5,0.5,1.0,1.0,0.5,0.5]
}
HAPPY_PARAMS = {
    'scale': [0,2,4,5,7,9,11], 'root': 62, 'tempo': 120,
    'chords': [[0,4,7],[5,9,0],[7,11,2],[0,4,7]],
    'rhythm': [0.5,0.5,0.25,0.25,0.5,0.5,0.5]
}
CALM_PARAMS = {
    'scale': [0,2,4,7,9], 'root': 60, 'tempo': 85,
    'chords': [[0,4,7],[2,7,9],[4,7,0],[0,4,7]],
    'rhythm': [0.75,0.25,1.0,0.5,0.5,1.0]
}

PARAMS = {'sad': SAD_PARAMS, 'happy': HAPPY_PARAMS, 'calm': CALM_PARAMS}


def apply_prompt_influence(p, prompt_emb):
    # use the learned prompt stats to nudge tempo
    pmean = prompt_emb.mean().item()
    pstd = prompt_emb.std().item()
    adj = 1.0 + (pmean * 0.3)
    p['tempo'] = int(p['tempo'] * adj)
    if pstd > 0.5:
        p['rhythm'] = [r * random.uniform(0.8,1.2) for r in p['rhythm']]
    return p


def make_melody(scale, root, beat_dur, rhythm, nbars):
    notes = []
    t = 0
    deg = 0
    for bar in range(nbars):
        for r in rhythm:
            if notes and random.random() < 0.7:
                deg = (deg + random.choice([-1,1])) % len(scale)
            elif notes:
                deg = random.randint(0, len(scale)-1)

            p = root + scale[deg] + random.choice([0,12,-12])
            p = max(48, min(84, p))
            dur = int(beat_dur * r)
            notes.append({'pitch':p, 'time':t, 'duration':dur, 'velocity':random.randint(55,85)})
            t += dur
    return notes


def make_chords(chords_prog, root, beat_dur, nbars):
    out = []
    t = 0
    for bar in range(nbars):
        if bar%2==0:
            ch = chords_prog[bar//2 % len(chords_prog)]
        dur = beat_dur*4
        for d in ch:
            p = max(36, min(72, root+d-12))
            out.append({'pitch':p,'time':t,'duration':dur,'velocity':random.randint(40,60)})
        t += dur
    return out


def make_bass(chords_prog, root, beat_dur, nbars):
    out = []
    t = 0
    for bar in range(nbars):
        cr = chords_prog[bar//2 % len(chords_prog)][0]
        p = max(28, min(48, root+cr-24))
        out.append({'pitch':p,'time':t,'duration':beat_dur*2,'velocity':random.randint(60,80)})
        out.append({'pitch':p+7,'time':t+beat_dur*2,'duration':beat_dur*2,'velocity':random.randint(50,70)})
        t += beat_dur*4
    return out


def generate_midi(emotion, prompt_emb, nbars, outpath):
    p = dict(PARAMS[emotion])  # copy so we dont mutate the original
    p['rhythm'] = list(p['rhythm'])
    p['chords'] = list(p['chords'])
    p = apply_prompt_influence(p, prompt_emb)

    beat_dur = int((60/p['tempo'])*480)

    mel = make_melody(p['scale'], p['root'], beat_dur, p['rhythm'], nbars)
    chd = make_chords(p['chords'], p['root'], beat_dur, nbars)
    bas = make_bass(p['chords'], p['root'], beat_dur, nbars)

    score = symusic.Score()
    score.tpq = 480
    mel_track = symusic.Track(name="Melody",program=0,is_drum=False)
    chd_track = symusic.Track(name="Chords",program=0,is_drum=False)
    bas_track = symusic.Track(name="Bass",program=32,is_drum=False)

    for n in mel:
        mel_track.notes.append(symusic.Note(time=n['time'],duration=n['duration'],pitch=n['pitch'],velocity=n['velocity']))
    for n in chd:
        chd_track.notes.append(symusic.Note(time=n['time'],duration=n['duration'],pitch=n['pitch'],velocity=n['velocity']))
    for n in bas:
        bas_track.notes.append(symusic.Note(time=n['time'],duration=n['duration'],pitch=n['pitch'],velocity=n['velocity']))

    score.tracks.extend([mel_track, chd_track, bas_track])
    score.dump_midi(outpath)
    return (nbars*4*60)/p['tempo']


def load_training_data(folder="midi_files"):
    data = []
    if not os.path.exists(folder): return data
    for mp in tqdm(list(Path(folder).glob("*.mid")), desc="Loading MIDI data"):
        try:
            if mp.name not in EMOTION_LABELS: continue
            s = symusic.Score(str(mp))
            toks = []
            for tr in s.tracks[:2]:
                for n in tr.notes[:100]:
                    toks += [n.pitch, min(n.velocity,127), min(int(n.duration/100),50)]
            if len(toks)>50:
                data.append({'tokens':toks[:256], 'emotion':EMOTION_LABELS[mp.name]})
        except: continue
    return data


def train_prompts(model, prompts, data, epochs=60):
    opt = torch.optim.AdamW(prompts.parameters(), lr=0.0008, weight_decay=0.01)
    lossfn = nn.CrossEntropyLoss()
    dev = next(model.parameters()).device

    for ep in range(epochs):
        tot = 0; nb = 0
        np.random.shuffle(data)
        for item in data:
            toks = item['tokens'][:256]
            if len(toks)<30: continue

            prompt = prompts.get(item['emotion']).unsqueeze(0)
            ids = torch.tensor([[min(t,3238) for t in toks]], dtype=torch.long).to(dev)
            emb = model.transformer.wte(ids)
            inp = torch.cat([prompt, emb], dim=1)

            out = model(inputs_embeds=inp)
            logits = out.logits[:, prompt.shape[1]-1:-1, :]
            loss = lossfn(logits.reshape(-1, logits.shape[-1]), ids.reshape(-1))

            opt.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(prompts.parameters(), 0.5)
            opt.step()
            tot += loss.item(); nb += 1

        if (ep+1)%10==0:
            print("  Epoch %d/%d, Loss: %.4f" % (ep+1, epochs, tot/max(nb,1)))


def main():
    extract_and_convert()

    # load skytnt
    dev = 'cuda' if torch.cuda.is_available() else 'cpu'
    try:
        from huggingface_hub import hf_hub_download
        from safetensors.torch import load_file
        mp = hf_hub_download(repo_id="skytnt/midi-model", filename="model.safetensors")
        cfg = GPT2Config(vocab_size=3239, n_positions=2048, n_embd=1024, n_layer=12, n_head=16)
        model = GPT2LMHeadModel(cfg).to(dev)
        model.load_state_dict(load_file(mp), strict=False)
    except:
        cfg = GPT2Config(vocab_size=3239, n_positions=2048, n_embd=1024, n_layer=12, n_head=16)
        model = GPT2LMHeadModel(cfg).to(dev)

    for p in model.parameters(): p.requires_grad = False

    prompts = EmotionPrompts().to(dev)
    data = load_training_data()

    if len(data)>=5:
        train_prompts(model, prompts, data, epochs=60)

    # generate the actual pieces
    for emo in ['sad','happy','calm']:
        prompts.eval()
        model.eval()
        with torch.no_grad():
            pemb = prompts.get(emo)
        for nbars, tag in [(32,"medium"),(64,"long")]:
            fname = "%s_%s.mid" % (emo, tag)
            dur = generate_midi(emo, pemb, nbars, fname)
            print("Generated %s - %d bars, ~%.1fs" % (fname, nbars, dur))


if __name__=="__main__":
    main()