# -*- coding: utf-8 -*-
"""MIDI_to_Audio_Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1intLAQy9LV6Gy9uRu16n5L4TpYDNMSQX
"""

import subprocess
import sys
import os

subprocess.run([sys.executable, "-m", "pip", "install", "midi2audio", "pydub", "-q"])
subprocess.run(["apt-get", "install", "-y", "fluidsynth", "fluid-soundfont-gm", "ffmpeg"], capture_output=True)

from midi2audio import FluidSynth
from pydub import AudioSegment

fs = FluidSynth("/usr/share/sounds/sf2/FluidR3_GM.sf2")

fs.midi_to_audio("sad_long.mid", "sad_long.wav")
fs.midi_to_audio("happy_long.mid", "happy_long.wav")
fs.midi_to_audio("calm_long.mid", "calm_long.wav")

AudioSegment.from_wav("sad_long.wav").export("sad_long.mp3", format="mp3", bitrate="192k")
AudioSegment.from_wav("happy_long.wav").export("happy_long.mp3", format="mp3", bitrate="192k")
AudioSegment.from_wav("calm_long.wav").export("calm_long.mp3", format="mp3", bitrate="192k")